package survey

import (
	"os"
	"path/filepath"
	"testing"
)

// write creates a file under a fresh temp root and returns the root.
func write(t *testing.T, rel, content string) string {
	t.Helper()
	root := t.TempDir()
	path := filepath.Join(root, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
	return root
}

func TestDetectsCanonicalMarker(t *testing.T) {
	root := write(t, "api/thing.pb.go",
		"// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage api\n")
	if !newGeneratedDetector(root).isGenerated("api/thing.pb.go") {
		t.Error("canonical marker must be detected")
	}
}

// TestMarkerAfterPackageClauseIsNotGenerated pins the stop rule: the
// convention puts the marker before the first non-comment line, so a matching
// line in the body is not a generated-code declaration.
func TestMarkerAfterPackageClauseIsNotGenerated(t *testing.T) {
	root := write(t, "a.go",
		"package a\n\n// Code generated by hand. DO NOT EDIT.\nvar X = 1\n")
	if newGeneratedDetector(root).isGenerated("a.go") {
		t.Error("a marker after the package clause must not count")
	}
}

func TestNearMissMarkersAreNotGenerated(t *testing.T) {
	cases := map[string]string{
		"no DO NOT EDIT":   "// Code generated by protoc-gen-go.\n\npackage a\n",
		"not a whole line": "// x // Code generated by y. DO NOT EDIT.\n\npackage a\n",
		"missing period":   "// Code generated by y. DO NOT EDIT\n\npackage a\n",
		"no marker":        "// Package a does things.\n\npackage a\n",
		"block comment":    "/* Code generated by y. DO NOT EDIT. */\n\npackage a\n",
	}
	for name, content := range cases {
		t.Run(name, func(t *testing.T) {
			root := write(t, "a.go", content)
			if newGeneratedDetector(root).isGenerated("a.go") {
				t.Errorf("%s must not count as generated", name)
			}
		})
	}
}

// TestUnreadableFileIsHandWritten pins the asymmetric default: a false
// EXCLUSION silently drops real work out of the queue, where nobody will look
// for it again. A false inclusion only leaves noise in a table someone reads.
func TestUnreadableFileIsHandWritten(t *testing.T) {
	d := newGeneratedDetector(t.TempDir())
	if d.isGenerated("does/not/exist.go") {
		t.Error("a missing file must count as hand-written")
	}
	if d.isGenerated("") {
		t.Error("an empty path must count as hand-written")
	}
}

// TestNilDetectorIsHandWritten lets callers pass a nil detector to mean
// "classify nothing", which the survey's own tests rely on.
func TestNilDetectorIsHandWritten(t *testing.T) {
	var d *generatedDetector
	if d.isGenerated("a.go") {
		t.Error("nil detector must answer false")
	}
}

// TestFileReadOnce pins memoization: hundreds of reported functions share one
// generated file. Deleting the file after the first call proves the second
// answer came from the memo rather than from disk.
func TestFileReadOnce(t *testing.T) {
	root := write(t, "a.go", "// Code generated by y. DO NOT EDIT.\n\npackage a\n")
	d := newGeneratedDetector(root)
	if !d.isGenerated("a.go") {
		t.Fatal("first call must detect the marker")
	}
	if err := os.Remove(filepath.Join(root, "a.go")); err != nil {
		t.Fatal(err)
	}
	if !d.isGenerated("a.go") {
		t.Error("second call must be served from the memo")
	}
}
