// Package trust scaffolds a trust file: the bounds a user asserts for code
// they cannot edit, so their own functions get verdicts and their budgets
// become enforceable.
//
// It suggests KEYS and never bounds. A tool that guessed a bound would be
// inventing the claim it exists to check, so every generated line is commented
// out and carries a placeholder that fails to parse if uncommented unedited.
//
// Candidates are ranked by GRADUATION count — how many of the user's functions
// a key alone would unblock — never by call sites, because clearing one blocker
// usually reveals the next.
//
// Two kinds of blocker are filtered out, and both filters ask an authority
// rather than a string:
//
//   - no cost-table key at all (interface dispatch, function values, builtins)
//     means no trust entry can name it, and the key's absence says so.
//   - a key the curated table ALREADY answers cannot be helped either: the
//     curated tables outrank an assumption, so the entry would be shadowed. This
//     is the "unresolved ARGUMENT SIZE at call to X" shape, where X is priced
//     and only the argument's size is unknown.
//
// The second filter was missing when this shipped, and the first real run
// against outside repositories offered keys that could do nothing.
//
// This package sits between report and frontier rather than inside either: it
// needs report to build the document and frontier to rank it, and frontier
// already depends on report.
package trust

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/RomanAgaltsev/bigo/internal/assume"
	"github.com/RomanAgaltsev/bigo/internal/costtable"
	"github.com/RomanAgaltsev/bigo/internal/frontier"
	"github.com/RomanAgaltsev/bigo/internal/kata"
	"github.com/RomanAgaltsev/bigo/internal/report"
)

// trustHeader tells the reader what a trust entry IS before they write one.
// Three things it must say, and each is load-bearing:
//
//   - bigo will BELIEVE an entry. A trusted bound is the user's claim, never
//     bigo's inference, and nothing downstream can tell the difference except
//     the provenance field.
//   - the counts are GRADUATION counts, not call sites, and they do not add up,
//     because clearing one blocker usually reveals the next.
//   - only single blockers are listed, so the file is a starting point and
//     never an inventory.
const trustHeader = "# bigo trust file — generated by `bigo trust init`.\n" +
	"#\n" +
	"# Each line below is a bound bigo CANNOT infer and will BELIEVE if you assert\n" +
	"# it. Uncomment a line, replace the bound, and add one line saying why you\n" +
	"# believe it. An entry with no justification is a bound nobody has reasoned\n" +
	"# about.\n" +
	"#\n"

// measuredClause and predictedClause are the two things the count can BE, and
// the file must say which one it is carrying.
//
// The header used to assert "MEASURED" unconditionally while measureCandidates
// failed soft to the predicted count, so on that path the file stated a
// property of itself that was false (2026-08-12 review F4). An unconditional
// claim over a best-effort computation is the same defect v1.44.2 fixed by
// putting the caveat in the file at all; this puts the RIGHT caveat in it.
const measuredClause = "# The counts are MEASURED, not predicted: bigo re-analysed your module with\n" +
	"# each key priced and counted what actually became verifiable. They are\n" +
	"# functions in YOUR module that this key ALONE unblocks, never call sites,\n" +
	"# and clearing one blocker usually reveals the next, so they do not add up.\n" +
	"#\n" +
	"# Each count is an UPPER BOUND, reached only by a CONSTANT bound. If your\n" +
	"# honest bound is in terms of an argument's size, the caller also needs that\n" +
	"# size to resolve at the call site, and often it does not — so a truthful\n" +
	"# O(n) entry can deliver far less than the number beside it.\n"

const predictedClause = "# WARNING: the counts below are PREDICTED, not measured. bigo could not\n" +
	"# re-analyse your module with the keys priced, so each number is the count of\n" +
	"# functions whose only recorded blocker is that key — which overstates what\n" +
	"# asserting it delivers, because a bound in terms of an argument's size also\n" +
	"# needs that size to resolve at the call site. Treat them as a ranking, not\n" +
	"# as a promise.\n"

const trustFooterNotes = "#\n" +
	"# Only single blockers are listed. A function waiting on two keys needs both\n" +
	"# trusted at once and is not shown; this file is a starting point, not an\n" +
	"# inventory.\n" +
	"#\n" +
	"# GENERATED CODE COUNTS. Machine-written files in your module are scored like\n" +
	"# any other, so a protobuf- or mock-heavy module can rank a key highly on the\n" +
	"# strength of code nobody reads. Check what a key's callers actually are\n" +
	"# before you spend reasoning on it.\n"

// headerFor renders the header for a file whose counts are measured or not.
func headerFor(measured bool) string {
	clause := predictedClause
	if measured {
		clause = measuredClause
	}
	return trustHeader + clause + trustFooterNotes
}

// trustInit renders the starter file for the module at dir.
//
// The document is built WITHOUT trust: the question it answers is what is
// blocking you now, so applying a trust file first would hide the very entries
// it is meant to suggest.
// measured is false when the probe pass could not run, so the caller can warn
// and the header can say which number the reader is holding.
func trustInit(dir string, kataMode bool) (text string, measured bool, err error) {
	l, err := report.LoadModule(dir, nil)
	if err != nil {
		return "", false, err
	}
	// The overlay must reach BOTH passes below: the ranking that decides which
	// keys are offered, and measureCandidates' re-analysis that prices them.
	// Applying it to one and not the other would rank under one cost model and
	// count under another, which is worse than answering the wrong model
	// consistently, because nothing in the output would show the split.
	opts := report.Options{Version: "trust-init"}
	if kataMode {
		profile, perr := kata.Profile()
		if perr != nil {
			// Hard error, never a skip. Ranking blockers under a cost model the
			// user did not get is exactly the defect this flag exists to fix.
			return "", false, fmt.Errorf("kata profile: %w", perr)
		}
		spaceProfile, perr := kata.SpaceProfile()
		if perr != nil {
			return "", false, fmt.Errorf("kata space profile: %w", perr)
		}
		opts.Overlay, opts.SpaceOverlay = profile, spaceProfile
	}
	doc, err := l.Document(opts)
	if err != nil {
		return "", false, err
	}
	fr := frontier.Of(doc)

	cands := make([]candidate, 0, len(fr.SoleBlockerCallee))
	for k, n := range fr.SoleBlockerCallee {
		// A key the curated table already answers cannot be helped by a trust
		// entry: both curated tables outrank an assumption, so the entry is
		// shadowed, warns, and changes no verdict. Such a blocker is real — the
		// argument's size is unknown — but it is not addressable here, and
		// offering it spends the user's reasoning on a line that does nothing.
		if costtable.Curated(k) {
			continue
		}
		cands = append(cands, candidate{k, n})
	}
	// Replace the PREDICTED count with a MEASURED one wherever the probe pass
	// succeeds. First contact measured the prediction as optimistic — goldmark
	// promised 29 and delivered 23 even with the best possible bound — and the
	// registered response to that was to redesign what is ranked, not to
	// document the discrepancy.
	// An empty candidate set is measured VACUOUSLY: there is no number to be
	// wrong about, and warning about it would train the reader to ignore the
	// warning that matters.
	measured = true
	if len(cands) > 0 {
		m, ok := measureCandidates(l, doc, cands, opts)
		if !ok {
			measured = false
		} else {
			cands = m
		}
	}

	// Descending by count, ties broken by key: determinism is a tested
	// property, so a regenerated file diffs cleanly rather than churning.
	sort.Slice(cands, func(i, j int) bool {
		if cands[i].count != cands[j].count {
			return cands[i].count > cands[j].count
		}
		return cands[i].key < cands[j].key
	})

	var b strings.Builder
	b.WriteString(headerFor(measured))
	for _, c := range cands {
		fmt.Fprintf(&b, "\n# %d of your functions are blocked only by this.\n", c.count)
		// O(...) is a PLACEHOLDER that does not parse. bigo suggests keys and
		// never bounds: guessing one would invent the claim it exists to check.
		fmt.Fprintf(&b, "# %s O(...)\n", c.key)
	}
	return b.String(), measured, nil
}

// InitMain is the `bigo trust init` driver. Exit codes match the other
// subcommands: 0 ok, 1 analysis or IO error, 2 flag error.
func InitMain(args []string) int {
	fs := flag.NewFlagSet("bigo trust init", flag.ContinueOnError)
	dir := fs.String("C", ".", "analyze the module in this directory")
	out := fs.String("o", "", "write to this file instead of stdout")
	force := fs.Bool("force", false, "overwrite an existing -o file")
	// Without this the command failed outright with "flag provided but not
	// defined" for a kata user — and parsing it is only half the fix. The
	// ranking must also be MEASURED under the model the user asked for, or it
	// recommends keys for a cost model they explicitly did not choose.
	kataMode := fs.Bool("kata", false,
		"rank blockers under the algorithm-kata cost model, matching `bigo -kata`")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	text, measured, err := trustInit(*dir, *kataMode)
	if err != nil {
		fmt.Fprintln(os.Stderr, "bigo trust init:", err)
		return 1
	}
	// Fail LOUD as well as honestly. The file says which number it carries, but
	// a user redirecting stdout to a file never reads the header before acting
	// on the ranking — and the whole point of the probe pass is that the two
	// numbers differ enough to matter.
	if !measured {
		fmt.Fprintln(os.Stderr, "bigo trust init: could not re-analyse with the candidate keys priced; "+
			"the counts are PREDICTED and overstate what asserting a key delivers")
	}
	if *out == "" {
		fmt.Print(text)
		return 0
	}
	// A trust file is hand-curated and carries the justifications someone
	// thought about; regenerating over it would destroy exactly that part.
	if _, err := os.Stat(*out); err == nil && !*force {
		fmt.Fprintf(os.Stderr, "bigo trust init: %s exists; pass -force to overwrite (your justifications will be lost)\n", *out)
		return 1
	}
	if err := os.WriteFile(*out, []byte(text), 0o600); err != nil {
		fmt.Fprintln(os.Stderr, "bigo trust init:", err)
		return 1
	}
	return 0
}

// candidate is one suggestion: a cost-table key and the number of the user's
// functions it would unblock.
type candidate struct {
	key   string
	count int
}

// measureCandidates replaces each candidate's PREDICTED count with a MEASURED
// one, by re-analysing the module once with every candidate asserted O(1) and
// attributing each newly-bounded function to the blocker it had been waiting on.
//
// Why a constant: it is the best case. A user's honest bound is a constant or it
// is not, and if it is not, the caller additionally needs the argument's size to
// resolve at the call site. So this number is an UPPER BOUND on what any bound
// can deliver — which is exactly what the old predicted count silently claimed
// to be and was not.
//
// The O(1) probe set is untruthful ON PURPOSE and never leaves this function: it
// produces a count, never a bound, and no document built from it is shown to
// anyone or written anywhere.
//
// Attribution by baseline sole-blocker is sound because cross-blocker
// interaction was measured at exactly zero, twice, in what-if campaign 1.
//
// ok=false means the probe could not run — an unmatched key, a load failure —
// and the caller keeps the predicted counts rather than failing the command.
// Scaffolding a file is worth doing with a worse number; it is not worth
// refusing to do.
func measureCandidates(l *report.Loaded, base report.Document, cands []candidate, opts report.Options) ([]candidate, bool) {
	if len(cands) == 0 {
		return cands, false
	}
	var b strings.Builder
	for _, c := range cands {
		fmt.Fprintf(&b, "%s O(1)\n", c.key)
	}
	entries, err := assume.ParseText(b.String())
	if err != nil {
		return nil, false
	}
	// Inherit the caller's cost model, then add the probe set: the measurement
	// is only meaningful against the same model the ranking used.
	probeOpts := opts
	probeOpts.Assume = assume.NewSet(entries)
	probe, err := l.Document(probeOpts)
	if err != nil {
		return nil, false
	}

	attributed := frontier.SoleBlockerIndex(base)
	wasTop := make(map[string]bool, len(base.Functions))
	for _, f := range base.Functions {
		if f.Time.Top {
			wasTop[frontier.PositionKey(f)] = true
		}
	}

	delivered := map[string]int{}
	for _, f := range probe.Functions {
		if f.Time.Top {
			continue
		}
		pos := frontier.PositionKey(f)
		if !wasTop[pos] {
			continue // already bounded before the probe
		}
		if key := attributed[pos]; key != "" {
			delivered[key]++
		}
	}

	out := make([]candidate, 0, len(cands))
	for _, c := range cands {
		// A candidate that delivers nothing is dropped rather than listed with a
		// zero: the file is a list of things worth doing.
		if n := delivered[c.key]; n > 0 {
			out = append(out, candidate{c.key, n})
		}
	}
	return out, true
}
