// Package trust scaffolds a trust file: the bounds a user asserts for code
// they cannot edit, so their own functions get verdicts and their budgets
// become enforceable.
//
// It suggests KEYS and never bounds. A tool that guessed a bound would be
// inventing the claim it exists to check, so every generated line is commented
// out and carries a placeholder that fails to parse if uncommented unedited.
//
// Candidates are ranked by GRADUATION count — how many of the user's functions
// a key alone would unblock — never by call sites, because clearing one blocker
// usually reveals the next. A blocker with no cost-table key (interface
// dispatch, function values) cannot be written into a trust file at all and is
// absent by construction rather than by a separate exclusion list.
//
// This package sits between report and frontier rather than inside either: it
// needs report to build the document and frontier to rank it, and frontier
// already depends on report.
package trust

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/RomanAgaltsev/bigo/internal/frontier"
	"github.com/RomanAgaltsev/bigo/internal/report"
)

// trustHeader tells the reader what a trust entry IS before they write one.
// Three things it must say, and each is load-bearing:
//
//   - bigo will BELIEVE an entry. A trusted bound is the user's claim, never
//     bigo's inference, and nothing downstream can tell the difference except
//     the provenance field.
//   - the counts are GRADUATION counts, not call sites, and they do not add up,
//     because clearing one blocker usually reveals the next.
//   - only single blockers are listed, so the file is a starting point and
//     never an inventory.
const trustHeader = "# bigo trust file — generated by `bigo trust init`.\n" +
	"#\n" +
	"# Each line below is a bound bigo CANNOT infer and will BELIEVE if you assert\n" +
	"# it. Uncomment a line, replace the bound, and add one line saying why you\n" +
	"# believe it. An entry with no justification is a bound nobody has reasoned\n" +
	"# about.\n" +
	"#\n" +
	"# The counts are functions in YOUR module that this key ALONE unblocks — not\n" +
	"# call sites. Clearing one blocker usually reveals the next, so the totals do\n" +
	"# not add up and are not a forecast.\n" +
	"#\n" +
	"# Only single blockers are listed. A function waiting on two keys needs both\n" +
	"# trusted at once and is not shown; this file is a starting point, not an\n" +
	"# inventory.\n"

// trustInit renders the starter file for the module at dir.
//
// The document is built WITHOUT trust: the question it answers is what is
// blocking you now, so applying a trust file first would hide the very entries
// it is meant to suggest.
func trustInit(dir string) (string, error) {
	l, err := report.LoadModule(dir, nil)
	if err != nil {
		return "", err
	}
	doc, err := l.Document(report.Options{Version: "trust-init"})
	if err != nil {
		return "", err
	}
	fr := frontier.Of(doc)

	type candidate struct {
		key   string
		count int
	}
	cands := make([]candidate, 0, len(fr.SoleBlockerCallee))
	for k, n := range fr.SoleBlockerCallee {
		cands = append(cands, candidate{k, n})
	}
	// Descending by graduation count, ties broken by key: determinism is a
	// tested property, so a regenerated file diffs cleanly rather than churning.
	sort.Slice(cands, func(i, j int) bool {
		if cands[i].count != cands[j].count {
			return cands[i].count > cands[j].count
		}
		return cands[i].key < cands[j].key
	})

	var b strings.Builder
	b.WriteString(trustHeader)
	for _, c := range cands {
		fmt.Fprintf(&b, "\n# %d of your functions are blocked only by this.\n", c.count)
		// O(...) is a PLACEHOLDER that does not parse. bigo suggests keys and
		// never bounds: guessing one would invent the claim it exists to check.
		fmt.Fprintf(&b, "# %s O(...)\n", c.key)
	}
	return b.String(), nil
}

// InitMain is the `bigo trust init` driver. Exit codes match the other
// subcommands: 0 ok, 1 analysis or IO error, 2 flag error.
func InitMain(args []string) int {
	fs := flag.NewFlagSet("bigo trust init", flag.ContinueOnError)
	dir := fs.String("C", ".", "analyze the module in this directory")
	out := fs.String("o", "", "write to this file instead of stdout")
	force := fs.Bool("force", false, "overwrite an existing -o file")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	text, err := trustInit(*dir)
	if err != nil {
		fmt.Fprintln(os.Stderr, "bigo trust init:", err)
		return 1
	}
	if *out == "" {
		fmt.Print(text)
		return 0
	}
	// A trust file is hand-curated and carries the justifications someone
	// thought about; regenerating over it would destroy exactly that part.
	if _, err := os.Stat(*out); err == nil && !*force {
		fmt.Fprintf(os.Stderr, "bigo trust init: %s exists; pass -force to overwrite (your justifications will be lost)\n", *out)
		return 1
	}
	if err := os.WriteFile(*out, []byte(text), 0o600); err != nil {
		fmt.Fprintln(os.Stderr, "bigo trust init:", err)
		return 1
	}
	return 0
}
